### ISSUE TITLE
Periodic scan is not changed by changing the CRON EXPRESSION in the Antivirus Job Scheduler

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-antivirus#22]
Preconditions: The Mail sending should be configured.

Steps to reproduce:

1. Log as Admin with proper email address set in profile
2. Access the Job Scheduler page (<xwiki name>/xwiki/bin/view/Scheduler)
3. Edit the Antivirus Job 
![AntivirusJob](https://user-images.githubusercontent.com/40691112/95730295-bb275480-0c86-11eb-8940-29b5b4be7a5d.jpg)
4. Change the "CRON EXPRESSION" eg. from default "59 59 23 ? * 1 *" (every Sun 23:59:59 CEST 2020) to "0 15 10 * * ?" (Fire at 10:15am every day) 
![Default](https://user-images.githubusercontent.com/40691112/95730335-cd08f780-0c86-11eb-8582-c2d983eb8f2f.jpg)
![Changed](https://user-images.githubusercontent.com/40691112/95730356-d1cdab80-0c86-11eb-8278-5086957fb959.jpg)
5. Save & View
6. Check the email address when the report email should be sent

Expected results: The scan is executed and the report email sent as configured.
"To configure how often the periodic scan is performed (default is once per week), edit the "Antivirus Job"'s "cron expression" from the Scheduler Application's jobs index."

Actual results: No scan is executed with the new configuration.
The email in this case was sent as per the default configuration - Sunday at 23.59
![EmailRecived](https://user-images.githubusercontent.com/40691112/95730386-dbefaa00-0c86-11eb-8fd2-0ae76b42b886.jpg)

Environment: Windows 10, Cloud demo instance XWiki 11.10.5, Antivirus Application 1.3

**Comment by acotiuga** [comment]
Hi @ane-gabriela! This is not an Antivirus app issue, but a Scheduler job behaviour. In order to get the expected result, a reschedule (Unschedule/Schedule) is needed.

**Comment by ane-gabriela** [comment]
Hi @acotiuga ! Thank you for your answer, indeed I've Unscheduled/Scheduled and the date is changed in the Job Scheduler page
![JobScheduler](https://user-images.githubusercontent.com/40691112/95743794-f895dd00-0c9a-11eb-9393-50129174c0a6.jpg)

Can anything be resolved for the use of the Antivirus app in this case? Or it will be left as a workaround, that we need to do this step every time we change the CRON EXPRESSION?

**Comment by acotiuga** [comment]
There is nothing that can or should be done in this particular case. Antivirus Job is the same as the others and this behaviour could be improvement in the Scheduler module.
