### ISSUE TITLE
Scheduled scan report displays "IOException: Broken pipe" error for files too large to be scanned

### ISSUE THREAD

**Issue by Enygma2002** [xwikisas/application-antivirus#24]
The ClamAV server can control the maximum allowed size of file to be scanned via network through the following setting:

* StreamMaxLength SIZE
Clamd uses FTP-like protocol to receive data from remote clients. If you are using clamav-milter to balance load between remote clamd daemons on firewall servers you may need to tune the Stream* options. This option allows you to specify the upper limit for data size that will be transfered to remote daemon when scanning a single file. It should match your MTA's limit for a maximum attachment size.
Default: 25M

Attempting to scan a file larger than the server limit will result in the server closing the connection, resulting in a `IOException: Broken pipe` error on the antivirus application.

This can happen during:
* file upload, making the scan fail and allowing the upload to pass through, unscanned.
* scheduled scan, when an error is recorded for the file that was failed to be scanned and the error will be included in the report.

The problem right now is that this error is quite ambiguous in the report and we could do a better job of displaying it in a more user friendly mode. Even if this exception can happen in other network related cases, we could simply say `File size too large`.

**Comment by aubincleme** [comment]
Hi,

We are getting several messages from customers about this issue on the XWiki Cloud platform.
@oanalavinia / @mflorea / @trrenty the option mentioned by Edy about the fact of putting "File size too large" in the report email seems nice, maybe we could consider adding it in a later release ?
